//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zodiac_Detail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zodiac_Detail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent and enigmatical, Aquarians are unique. There is no one quite like an Aquarius, and because each is so incredibly individual, it can be tough to describe them as a group. Aquarians don&apos;t like labels, and may shy away from any adjective—even the good ones you might bestow upon them. 
        ///
        ///Aquarians believe in the nature of change and evolution, and even though they&apos;re a fixed sign, they may not necessarily believe they are the &quot;same&quot; people they were when they were born..
        /// </summary>
        internal static string Aquarius {
            get {
                return ResourceManager.GetString("Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first sign of the Zodiac, Aries are the trailblazers. Passionate and independent, Aries will never do something just because everyone else is doing it—a Ram needs to be 100 percent committed to the task at hand. Competitive to the max, the best way to motivate an Aries is to turn something into a contest.
        ///
        ///Aries will put everything they have (and then some) into winning. Loyal, smart, and impulsive, they always have multiple projects on their mind, and won&apos;t be satisfied until their work, social life, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aries {
            get {
                return ResourceManager.GetString("Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotional, intuitive, and practically psychic; ruled by the moon and characterized by the crab, Cancer has so much going on in its watery depths. Cancer signs may seem prickly and standoffish at first meeting, once they make the decision to become friends with someone, that person has a friend for life..
        /// </summary>
        internal static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart, hardworking, and fully in control of their destiny, Capricorn signs will always get what they set their mind to, in both personal and professional life—no excuses. Capricorns may get a reputation as stubborn, but they simply know what they want, and also know how they wish other people would behave..
        /// </summary>
        internal static string Capricorn {
            get {
                return ResourceManager.GetString("Capricorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart, passionate, and dynamic, Gemini is characterized by the Twins, Castor and Pollux, and is known for having two different sides they can display to the world. Expert communicators, Gemini is the chameleon of the Zodiac, adept at blending into different groups based on the vibe and energy they perceive. While they&apos;re also amazing at showcasing surface traits, the Gemini well runs deep, which is why the Twins are one of the Zodiac&apos;s most emotionally intelligent signs..
        /// </summary>
        internal static string Gemini {
            get {
                return ResourceManager.GetString("Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold, intelligent, warm, and courageous, fire sign Leo is a natural leader of the Zodiac, ready to blaze a trail, vanquish injustice, and make a name for themselves along the way. Blessed with high self-esteem, Lions know that they possess enviable traits—and they&apos;re proud of them. 
        ///
        ///They don&apos;t believe in false modesty and will be the first to praise themselves for a job well done. But Leo isn&apos;t self-aggrandizing or unwilling to roll up those sleeves and do the work: this sign knows that in order to be re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leo {
            get {
                return ResourceManager.GetString("Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent, kind, and always willing to put others before themselves, Libras value harmony in all forms. Ruled by Venus, the planet of beauty, Libra adores a life that looks good. As the master of compromise and diplomacy, Libra is adept at seeing all points of view, and excels at crafting compromises and effecting mediation between others. 
        ///
        ///This sign has a rich inner life yet loves other people, and they&apos;re always happiest with a large group of friends, family, and coworkers on whom they can count..
        /// </summary>
        internal static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart, creative, and deeply intuitive, Pisces can be close to psychic. Pisces feel things deeply, and have incredibly strong gut reactions. A Pisces &quot;knows&quot; things from deep within, and can often judge whether a person or situation is good or bad. That doesn&apos;t mean a Pisces ignores the logical part of their brain, though. 
        ///
        ///Deeply intelligent, Pisces have a profound respect for the power of the human mind. Is it a surprise that Albert Einstein was a Pisces?.
        /// </summary>
        internal static string Pisces {
            get {
                return ResourceManager.GetString("Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent and strong-willed, Sagittarius personalities are all about going off the beaten path. Sagittarius isn’t afraid to step away from the pack, and is a natural born leader who goes after what he or she wants, regardless of what other people think. Sagittarius is a born adventurer, and loves solo travel and exploration. 
        ///
        ///Sagittarius also loves exploring the inner workings of their minds, and love stretching their horizons through a good book or movie..
        /// </summary>
        internal static string Sagittarius {
            get {
                return ResourceManager.GetString("Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passionate, independent, and unafraid to blaze their own trail no matter what others think, Scorpio signs make a statement wherever they go. They love debates, aren&apos;t afraid of controversy, and won&apos;t back down from a debate. They also hate people who aren&apos;t genuine, and are all about being authentic—even if authentic isn&apos;t pretty..
        /// </summary>
        internal static string Scorpio {
            get {
                return ResourceManager.GetString("Scorpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is a collection of the traits of all the zodiacs. To continue, you must click the three lines in the top left corner and select your desired zodiac sign.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart, ambitious, and trustworthy, Taurus is the anchor of the Zodiac. Amazing friends, colleagues, and partners, Taureans value honesty above all else and are proud that their personal relationships tend to be drama free.
        ///
        ///Bulls get the reputation of being stubborn, but they&apos;re not always stuck in their ways. This searching sign is willing to see another point of view, but they won&apos;t flip-flop on an opinion just to make someone else happy. They will shift their thinking only if they truly have a change o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tauros {
            get {
                return ResourceManager.GetString("Tauros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart, sophisticated, and kind, Virgo gets the job done without complaining. Virgos are amazing friends, always there to lend a hand and also lend advice. Practical Virgos are incredibly adept at big picture thinking, and planning out their life, their vacations, and what they&apos;re going to do today isn&apos;t a drag it makes them feel in control and secure..
        /// </summary>
        internal static string Virgo {
            get {
                return ResourceManager.GetString("Virgo", resourceCulture);
            }
        }
    }
}
